spring.application.name=ship-track-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/shiptrack
spring.datasource.username=postgres
spring.datasource.password=sHALEMrAJU22@#

spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true

jwt.secret_key=0e7f6b2d9c1a84f5e3d8b7a691c2ef4d5a9b8c7e6f1d2039485ab7c1d9e2f4a6c8b1d3e5f7a9c2e4d6b8f0a1c3e5d7f9
google.maps.api-key=AIzaSyDNuLWj5MboW4D7q4IF8cMxJwDRLoQzqFw