spring.application.name=ship-track-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/shiptrack
spring.datasource.username=postgres
spring.datasource.password=sHALEMrAJU22@#

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true